###

GET http://localhost:4000/notes

###
POST  http://localhost:4000/notes
Content-Type: application/json

{
    "title" : "Tugas Backend CRUD",
    "note" : "Panjang umur orang baik"
}

###
PUT http://localhost:4000/notes/title/2
Content-Type: application/json

{
    "title" : "Project Pawsitively",
}